import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import PieChart from '@/components/PieChart'
import RadarChart from '@/components/RadarChart'
import LineChart from '@/components/LineChart'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>Dashboard</h1>
        <div className={styles.row}>
        <div className={styles.chartContainer}>
        
          <RadarChart />
        </div>
        <div className={styles.chartContainer}>
        
          <PieChart />
          </div>
        </div>
        <div className={styles.bottom}>
        <LineChart />
        </div>
      </main>
    </>
  )
}
